---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: webapp
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
      env: demo
  template:
    metadata:
      labels:
        app: web-app
        env: demo
    spec:
      containers:
      - name: web-app
        image: ghcr.io/roberthstrand/demo-webapp:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: webapp
spec:
  selector:
    app: web-app
    env: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80